import Foundation

let SHARD_COUNT = UInt64(2**10)
let TARGET_COMMITTEE_SIZE = UInt64(2**7)
let EJECTION_BALANCE = UInt64((2**4) * Int(1e9))
let MAX_BALANCE_CHURN_QUOTIENT = UInt64(2**5)
let BEACON_CHAIN_SHARD_NUMBER = UInt64.max
let MAX_CASPER_VOTES = UInt64(2**10)
let LATEST_BLOCK_ROOTS_LENGTH = UInt64(2**13)
let LATEST_RANDAO_MIXES_LENGTH = UInt64(2**13)
let LATEST_PENALIZED_EXIT_LENGTH = UInt64(2**13)
let MAX_WITHDRAWALS_PER_EPOCH = UInt64(2**2)

let DEPOSIT_CONTRACT_TREE_DEPTH = UInt64(2**5)
let MIN_DEPOSIT_AMOUNT = UInt64(2**0 * Int(1e9))
let MAX_DEPOSIT_AMOUNT = UInt64(2**5 * Int(1e9))

let GENESIS_FORK_VERSION = UInt64(0)
let GENESIS_SLOT = UInt64(0)
let GENESIS_START_SHARD = UInt64(0)
let FAR_FUTURE_SLOT = UInt64.max
let ZERO_HASH = Data(repeating: 0, count: 32) // @todo unsure if this is bytes32(0x0)
let EMPTY_SIGNATURE = Data(repeating: 0, count: 48) // @todo unsure
let BLS_WITHDRAWAL_PREFIX_BYTE = 0x0

let SLOT_DURATION = UInt64(6)
let MIN_ATTESTATION_INCLUSION_DELAY = UInt64(2**2)
let EPOCH_LENGTH = UInt64(2**6)
let SEED_LOOKAHEAD = UInt64(2**6)
let ENTRY_EXIT_DELAY = UInt64(2**8)
let ETH1_DATA_VOTING_PERIOD = UInt64(2**10)
let MIN_VALIDATOR_WITHDRAWAL_TIME = UInt64(2**14)

let BASE_REWARD_QUOTIENT = UInt64(2**5)
let WHISTLEBLOWER_REWARD_QUOTIENT = UInt64(2**9)
let INCLUDER_REWARD_QUOTIENT = UInt64(2**3)
let INACTIVITY_PENALTY_QUOTIENT = UInt64(2**24)

let INITIATED_EXIT = UInt64(2**0)
let WITHDRAWABLE = UInt64(2**1)

let MAX_PROPOSER_SLASHINGS = UInt64(2**4)
let MAX_CASPER_SLASHINGS = UInt64(2**4)
let MAX_ATTESTATIONS = UInt64(2**7)
let MAX_DEPOSIT_AMOUNTS = UInt64(2**4)
let MAX_EXITS = UInt64(2**4)
