#if !canImport(ObjectiveC)
import XCTest

extension PowerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PowerTests = [
        ("testPowerForInt", testPowerForInt),
        ("testPowerForUInt64", testPowerForUInt64),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PowerTests.__allTests__PowerTests),
    ]
}
#endif
