#if !canImport(ObjectiveC)
import XCTest

extension ArrayAttestationTargetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayAttestationTargetTests = [
        ("testVotes", testVotes),
    ]
}

extension ArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayTests = [
        ("testSplit", testSplit),
    ]
}

extension ArrayValidatorIndexTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayValidatorIndexTests = [
        ("testTotalBalance", testTotalBalance),
    ]
}

extension ArrayValidatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayValidatorTests = [
        ("testActiveIndices", testActiveIndices),
    ]
}

extension BeaconChainTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BeaconChainTests = [
        ("testIntegerSquareRoot", testIntegerSquareRoot),
        ("testIsDoubleVote", testIsDoubleVote),
    ]
}

extension EpochTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EpochTests = [
        ("testEntryExitEpoch", testEntryExitEpoch),
        ("testStartSlot", testStartSlot),
    ]
}

extension ForkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ForkTests = [
        ("testDomain", testDomain),
        ("testVersion", testVersion),
    ]
}

extension IntTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntTests = [
        ("testIsPowerOfTwo", testIsPowerOfTwo),
    ]
}

extension SlotTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SlotTests = [
        ("testToEpoch", testToEpoch),
    ]
}

extension ValidatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValidatorTests = [
        ("testActivate", testActivate),
        ("testExitValidator", testExitValidator),
        ("testIsActive", testIsActive),
        ("testPrepareForWithdrawal", testPrepareForWithdrawal),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArrayAttestationTargetTests.__allTests__ArrayAttestationTargetTests),
        testCase(ArrayTests.__allTests__ArrayTests),
        testCase(ArrayValidatorIndexTests.__allTests__ArrayValidatorIndexTests),
        testCase(ArrayValidatorTests.__allTests__ArrayValidatorTests),
        testCase(BeaconChainTests.__allTests__BeaconChainTests),
        testCase(EpochTests.__allTests__EpochTests),
        testCase(ForkTests.__allTests__ForkTests),
        testCase(IntTests.__allTests__IntTests),
        testCase(SlotTests.__allTests__SlotTests),
        testCase(ValidatorTests.__allTests__ValidatorTests),
    ]
}
#endif
