import Foundation

// misc
let SHARD_COUNT = 2**10
let TARGET_COMMITTEE_SIZE = 2**7
let MAX_VALIDATORS_PER_COMMITTEE = 2**12
let MIN_PER_EPOCH_CHURN_LIMIT = 2**2
let CHURN_LIMIT_QUOTIENT = 2**16
let SHUFFLE_ROUND_COUNT = 90
let MIN_GENESIS_ACTIVE_VALIDATOR_COUNT = 2**16
let MIN_GENESIS_TIME = 1578009600
