import Foundation

// misc
let SHARD_COUNT = 2**10
let TARGET_COMMITTEE_SIZE = 2**7
let MAX_VALIDATORS_PER_COMMITTEE = 2**12
let MIN_PER_EPOCH_CHURN_LIMIT = 2**2
let CHURN_LIMIT_QUOTIENT = 2**16
let SHUFFLE_ROUND_COUNT = 90
let MIN_GENESIS_ACTIVE_VALIDATOR_COUNT = 2**16
let MIN_GENESIS_TIME = 1578009600

// gwei values
let MIN_DEPOSIT_AMOUNT = Gwei(2**0 * 10**9)
let MAX_EFFECTIVE_BALANCE = Gwei(2**5 * 10**9)
let EJECTION_BALANCE = Gwei(2**4 * 10**9)
let EFFECTIVE_BALANCE_INCREMENT = Gwei(2**0 * 10**9)

// initial values
let GENESIS_SLOT = Slot(0)
let GENESIS_EPOCH = Epoch(0)
let BLS_WITHDRAWAL_PREFIX = 0b00

// time parameters
let MIN_ATTESTATION_INCLUSION_DELAY = 2**0
let SLOTS_PER_EPOCH = 2**6
let MIN_SEED_LOOKAHEAD = 2**0
let ACTIVATION_EXIT_DELAY = 2**2
let SLOTS_PER_ETH1_VOTING_PERIOD = 2**10
let SLOTS_PER_HISTORICAL_ROOT = 2**13
let MIN_VALIDATOR_WITHDRAWABILITY_DELAY = 2**8
let PERSISTENT_COMMITTEE_PERIOD = 2**11
let MAX_EPOCHS_PER_CROSSLINK = 2**6
let MIN_EPOCHS_TO_INACTIVITY_PENALTY = 2**2

// state list lengths
let EPOCHS_PER_HISTORICAL_VECTOR = 2**16
let EPOCHS_PER_SLASHINGS_VECTOR = 2**13
let HISTORICAL_ROOTS_LIMIT = 2**14
let VALIDATOR_REGISTRY_LIMIT = 2**40

// rewards and penalties
let BASE_REWARD_FACTOR = 2**6
let WHISTLEBLOWER_REWARD_QUOTIENT = 2**9
let PROPOSER_REWARD_QUOTIENT = 2**3
let INACTIVITY_PENALTY_QUOTIENT = 2**25
let MIN_SLASHING_PENALTY_QUOTIENT = 2**5

// max operations per block
let MAX_PROPOSER_SLASHINGS = 2**4
let MAX_ATTESTER_SLASHINGS = 2**0
let MAX_ATTESTATIONS = 2**7
let MAX_DEPOSITS = 2**4
let MAX_VOLUNTARY_EXITS = 2**4
let MAX_TRANSFERS = 0
