import Foundation

// Misc
let SHARD_COUNT = UInt64(2**10)
let TARGET_COMMITTEE_SIZE = UInt64(2**7)
let MAX_BALANCE_CHURN_QUOTIENT = UInt64(2**5)
let MAX_INDICES_PER_SLASHABLE_VOTE = UInt64(2**12)
let MAX_EXIT_DEQUEUES_PER_EPOCH = UInt64(2**2)
let SHUFFLE_ROUND_COUNT = 90

// Deposit Contract
//let DEPOSIT_CONTRACT_ADDRESS =
let DEPOSIT_CONTRACT_TREE_DEPTH = UInt64(2**5)

// GWEI Values
let MIN_DEPOSIT_AMOUNT = UInt64(2**0 * UInt64(1e9))
let MAX_DEPOSIT_AMOUNT = UInt64(2**5 * UInt64(1e9))
let FORK_CHOICE_BALANCE_INCREMENT = UInt64(2**0 * UInt64(1e9))
let EJECTION_BALANCE = UInt64(2**4 * UInt64(1e9))

// Initial Values
let GENESIS_FORK_VERSION = UInt64(0)
let GENESIS_SLOT = UInt64(2**32)
let GENESIS_EPOCH = Slot(GENESIS_SLOT).toEpoch()
let GENESIS_START_SHARD = UInt64(0)
let FAR_FUTURE_EPOCH = UInt64.max
let ZERO_HASH = Data(repeating: 0, count: 32) // @todo create type
let EMPTY_SIGNATURE = Data(repeating: 0, count: 96)
let BLS_WITHDRAWAL_PREFIX_BYTE = Data(repeating: 0, count: 1)

// Time parameters
let SECONDS_PER_SLOT = UInt64(6)
let MIN_ATTESTATION_INCLUSION_DELAY = UInt64(2**2)
let SLOTS_PER_EPOCH = UInt64(2**6)
let MIN_SEED_LOOKAHEAD = UInt64(2**0)
let ACTIVATION_EXIT_DELAY = UInt64(2**2)
let EPOCHS_PER_ETH1_VOTING_PERIOD = UInt64(2**4)
let SLOTS_PER_HISTORICAL_ROOT = UInt64(2**13)
let MIN_VALIDATOR_WITHDRAWABILITY_DELAY = UInt64(2**8)
let PERSISTENT_COMMITTEE_PERIOD = UInt64(2**11)

// State list lengths
let LATEST_RANDAO_MIXES_LENGTH = UInt64(2**13)
let LATEST_ACTIVE_INDEX_ROOTS_LENGTH = UInt64(2**13)
let LATEST_SLASHED_EXIT_LENGTH = UInt64(2**13)

// Reward and penalty quotients
let BASE_REWARD_QUOTIENT = UInt64(2**5)
let WHISTLEBLOWER_REWARD_QUOTIENT = UInt64(2**9)
let ATTESTATION_INCLUSION_REWARD_QUOTIENT = UInt64(2**3)
let INACTIVITY_PENALTY_QUOTIENT = UInt64(2**24)
let MIN_PENALTY_QUOTIENT = UInt64(2**5)

// Max transactions per block
let MAX_PROPOSER_SLASHINGS = UInt64(2**4)
let MAX_ATTESTER_SLASHINGS = UInt64(2**0)
let MAX_ATTESTATIONS = UInt64(2**7)
let MAX_DEPOSITS = UInt64(2**4)
let MAX_VOLUNTARY_EXITS = UInt64(2**4)
let MAX_TRANSFERS = UInt64(2**4)
