import Foundation

// Misc
let SHARD_COUNT = UInt64(2**10)
let TARGET_COMMITTEE_SIZE = UInt64(2**7)
let MAX_BALANCE_CHURN_QUOTIENT = UInt64(2**5)
let BEACON_CHAIN_SHARD_NUMBER = UInt64.max
let MAX_INDICES_PER_SLASHABLE_VOTE = UInt64(2**12)
let MAX_WITHDRAWALS_PER_EPOCH = UInt64(2**2)
let SHUFFLE_ROUND_COUNT = 90

// Deposit Contract
//let DEPOSIT_CONTRACT_ADDRESS =
let DEPOSIT_CONTRACT_TREE_DEPTH = UInt64(2**5)

// GWEI Values
let MIN_DEPOSIT_AMOUNT = UInt64(2**0 * UInt64(1e9))
let MAX_DEPOSIT_AMOUNT = UInt64(2**5 * UInt64(1e9))
let FORK_CHOICE_BALANCE_INCREMENT = UInt64(2**0 * UInt64(1e9))
let EJECTION_BALANCE = UInt64(2**4 * UInt64(1e9))

// Initial Values
let GENESIS_FORK_VERSION = UInt64(0)
let GENESIS_SLOT = UInt64(2**19)
let GENESIS_EPOCH = BeaconChain.slotToEpoch(GENESIS_SLOT)
let GENESIS_START_SHARD = UInt64(0)
let FAR_FUTURE_EPOCH = UInt64.max
let ZERO_HASH = Data(repeating: 0, count: 32) // @todo create type
let EMPTY_SIGNATURE = Data(repeating: 0, count: 96)
let BLS_WITHDRAWAL_PREFIX_BYTE = Data(repeating: 0, count: 1)

// Time parameters
let SLOT_DURATION = UInt64(6)
let MIN_ATTESTATION_INCLUSION_DELAY = UInt64(2**2)
let EPOCH_LENGTH = UInt64(2**6)
let SEED_LOOKAHEAD = UInt64(2**0)
let ENTRY_EXIT_DELAY = UInt64(2**2)
let ETH1_DATA_VOTING_PERIOD = UInt64(2**4)
let MIN_VALIDATOR_WITHDRAWAL_EPOCHS = UInt64(2**8)

// State list lengths
let LATEST_BLOCK_ROOTS_LENGTH = UInt64(2**13)
let LATEST_RANDAO_MIXES_LENGTH = UInt64(2**13)
let LATEST_INDEX_ROOTS_LENGTH = UInt64(2**13)
let LATEST_PENALIZED_EXIT_LENGTH = UInt64(2**13)

// Reward and penalty quotients
let BASE_REWARD_QUOTIENT = UInt64(2**5)
let WHISTLEBLOWER_REWARD_QUOTIENT = UInt64(2**9)
let INCLUDER_REWARD_QUOTIENT = UInt64(2**3)
let INACTIVITY_PENALTY_QUOTIENT = UInt64(2**24)

// Max operations per block
let MAX_PROPOSER_SLASHINGS = UInt64(2**4)
let MAX_ATTESTER_SLASHINGS = UInt64(2**0)
let MAX_ATTESTATIONS = UInt64(2**7)
let MAX_DEPOSITS = UInt64(2**4)
let MAX_EXITS = UInt64(2**4)
