import Foundation

let FAR_FUTURE_EPOCH = Epoch(UInt64.max)
let BASE_REWARDS_PER_EPOCH = 5
let DEPOSIT_CONTRACT_TREE_DEPTH = 2**5
let SECONDS_PER_DAY = 86400
let JUSTIFICATION_BITS_LENGTH = 4
let ENDIANNESS = "little"
